[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://same-4h9hy38yrn1-latest.netlify.app"
  NODE_VERSION = "20"

[images]
  remote_images = ["https://ext.same-assets.com/*"]
